#!/bin/sh

FLUENTD_VERSION=$(fluentd --version | cut -d ' ' -f 2)
GEM_S3=$(gem list | grep -E "fluent-plugin-s3")
GEM_S3_NAME=$(echo ${GEM_S3} | cut -d " " -f 1)
GEM_S3_VERSION=$(echo ${GEM_S3} | cut -d " " -f 2 | tr -d '()')
GEM_ES=$(gem list | grep -E "fluent-plugin-elasticsearch")
GEM_ES_NAME=$(echo ${GEM_ES} | cut -d " " -f 1)
GEM_ES_VERSION=$(echo ${GEM_ES} | cut -d " " -f 2 | tr -d '()')

printf -- "fluentd:${FLUENTD_VERSION}\n";
printf -- "${GEM_S3_NAME}:${GEM_S3_VERSION}\n";
printf -- "${GEM_ES_NAME}:${GEM_ES_VERSION}\n";
